use std::io::{self, Write};
use std::path::PathBuf;

use argon2::password_hash::rand_core::OsRng;
use argon2::password_hash::SaltString;
use argon2::{Argon2, PasswordHasher};

/// Run the interactive first-time setup.
/// Creates config directory, generates JWT secret, hashes password, writes .env.
pub async fn run_init() -> anyhow::Result<()> {
    let home = std::env::var("HOME").unwrap_or_else(|_| String::from("/root"));
    let config_dir = PathBuf::from(&home).join("cron-rs");

    println!("=== cron-rs interactive setup ===");
    println!();

    // Prompt for username
    print!("Admin username [admin]: ");
    io::stdout().flush()?;
    let mut username = String::new();
    io::stdin().read_line(&mut username)?;
    let username = username.trim();
    let username = if username.is_empty() { "admin" } else { username };

    // Prompt for password
    print!("Admin password: ");
    io::stdout().flush()?;
    let mut password = String::new();
    io::stdin().read_line(&mut password)?;
    let password = password.trim().to_string();

    if password.is_empty() {
        anyhow::bail!("Password cannot be empty");
    }

    // Confirm password
    print!("Confirm password: ");
    io::stdout().flush()?;
    let mut confirm = String::new();
    io::stdin().read_line(&mut confirm)?;
    let confirm = confirm.trim();

    if password != confirm {
        anyhow::bail!("Passwords do not match");
    }

    // Hash password with argon2
    println!("Hashing password...");
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    let password_hash = argon2
        .hash_password(password.as_bytes(), &salt)
        .map_err(|e| anyhow::anyhow!("Failed to hash password: {}", e))?
        .to_string();

    // Generate random JWT secret (32 bytes hex)
    let mut jwt_bytes = [0u8; 32];
    use rand::RngCore;
    rand::thread_rng().fill_bytes(&mut jwt_bytes);
    let jwt_secret = hex::encode(jwt_bytes);

    // Ensure config directory exists
    std::fs::create_dir_all(&config_dir)?;

    // Build .env content
    let db_path = config_dir.join("cron-rs.db");
    let env_content = format!(
        r#"# cron-rs configuration
# Generated by `cron-rs init`

CRON_RS_USERNAME={username}
CRON_RS_PASSWORD={password_hash}
CRON_RS_JWT_SECRET={jwt_secret}
CRON_RS_HOST=127.0.0.1
CRON_RS_PORT=9746
CRON_RS_DB={db_path}
CRON_RS_TOKEN_EXPIRY=24h
CRON_RS_CONFIG_DIR={config_dir}
"#,
        username = username,
        password_hash = password_hash,
        jwt_secret = jwt_secret,
        db_path = db_path.display(),
        config_dir = config_dir.display(),
    );

    let env_path = config_dir.join(".env");
    std::fs::write(&env_path, &env_content)?;

    println!();
    println!("Configuration written to: {}", env_path.display());
    println!();
    println!("Next steps:");
    println!("  1. Start the daemon:  cron-rs daemon");
    println!("  2. Create a task:     cron-rs task create my-task --command 'echo hello' --schedule '*-*-* *:00:00'");
    println!("  3. View tasks:        cron-rs task list");
    println!("  4. Check status:      cron-rs status");
    println!();
    println!("The .env file is loaded automatically from ~/cron-rs/.env");

    Ok(())
}
