use std::io::{self, Write};

use argon2::password_hash::rand_core::OsRng;
use argon2::password_hash::SaltString;
use argon2::{Argon2, PasswordHasher};

use crate::config::Config;

#[derive(Debug, Default)]
pub struct InitOptions {
    pub username: Option<String>,
    pub password: Option<String>,
    pub host: Option<String>,
    pub port: Option<u16>,
    pub config_dir: Option<String>,
    pub db_path: Option<String>,
}

/// Run the interactive first-time setup.
/// Creates config directory, generates JWT secret, hashes password, writes .env.
pub async fn run_init(options: InitOptions) -> anyhow::Result<()> {
    let home = std::env::var("HOME").unwrap_or_else(|_| String::from("/root"));
    let has_cli_options = options.username.is_some()
        || options.password.is_some()
        || options.host.is_some()
        || options.port.is_some()
        || options.config_dir.is_some()
        || options.db_path.is_some();
    let config_dir = options
        .config_dir
        .as_deref()
        .map(|p| Config::expand_path(p, &home))
        .unwrap_or_else(|| Config::default_config_dir_for_home(&home));

    println!("=== cron-rs setup ===");
    println!();

    let username = match options.username {
        Some(username) if !username.trim().is_empty() => username.trim().to_string(),
        _ if has_cli_options => "admin".to_string(),
        _ => prompt_with_default("Admin username", "admin")?,
    };

    let password_arg_provided = options.password.is_some();
    let password = match options.password {
        Some(password) => password,
        None => prompt_required("Admin password")?,
    };

    if password.is_empty() {
        anyhow::bail!("Password cannot be empty");
    }

    if !password_arg_provided {
        let confirm = prompt_required("Confirm password")?;

        if password != confirm {
            anyhow::bail!("Passwords do not match");
        }
    }

    let host = options.host.unwrap_or_else(|| "127.0.0.1".to_string());
    let port = options.port.unwrap_or(9746);

    // Hash password with argon2
    println!("Hashing password...");
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    let password_hash = argon2
        .hash_password(password.as_bytes(), &salt)
        .map_err(|e| anyhow::anyhow!("Failed to hash password: {}", e))?
        .to_string();

    // Generate random JWT secret (32 bytes hex)
    let mut jwt_bytes = [0u8; 32];
    use rand::RngCore;
    rand::thread_rng().fill_bytes(&mut jwt_bytes);
    let jwt_secret = hex::encode(jwt_bytes);

    // Ensure config directory exists
    std::fs::create_dir_all(&config_dir)?;

    // Build .env content
    let db_path = options
        .db_path
        .as_deref()
        .map(|p| Config::expand_path(p, &home))
        .unwrap_or_else(|| config_dir.join("cron-rs.db"));
    let env_content = format!(
        r#"# cron-rs configuration
# Generated by `cron-rs init`

CRON_RS_USERNAME={username}
CRON_RS_PASSWORD={password_hash}
CRON_RS_JWT_SECRET={jwt_secret}
CRON_RS_HOST={host}
CRON_RS_PORT={port}
CRON_RS_DB={db_path}
CRON_RS_TOKEN_EXPIRY=24h
CRON_RS_CONFIG_DIR={config_dir}
"#,
        username = dotenv_quote(&username),
        password_hash = dotenv_quote(&password_hash),
        jwt_secret = dotenv_quote(&jwt_secret),
        host = dotenv_quote(&host),
        port = port,
        db_path = dotenv_quote(&db_path.display().to_string()),
        config_dir = dotenv_quote(&config_dir.display().to_string()),
    );

    let env_path = config_dir.join(".env");
    std::fs::write(&env_path, &env_content)?;

    println!();
    println!("Configuration written to: {}", env_path.display());
    println!();
    println!("Next steps:");
    println!("  1. Import existing schedules: cron-rs import");
    println!("  2. Start the daemon:          cron-rs daemon");
    println!(
        "  3. Create a task:             cron-rs task create my-task --command 'echo hello' --schedule '*-*-* *:00:00'"
    );
    println!("  4. View tasks:                cron-rs task list");
    println!("  5. Check status:              cron-rs status");
    println!();
    println!(
        "The .env file is loaded automatically from {}",
        env_path.display()
    );

    Ok(())
}

fn prompt_with_default(label: &str, default: &str) -> anyhow::Result<String> {
    print!("{label} [{default}]: ");
    io::stdout().flush()?;
    let mut value = String::new();
    io::stdin().read_line(&mut value)?;
    let value = value.trim();
    Ok(if value.is_empty() {
        default.to_string()
    } else {
        value.to_string()
    })
}

fn prompt_required(label: &str) -> anyhow::Result<String> {
    print!("{label}: ");
    io::stdout().flush()?;
    let mut value = String::new();
    io::stdin().read_line(&mut value)?;
    Ok(value.trim().to_string())
}

fn dotenv_quote(value: &str) -> String {
    format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'"))
}

#[cfg(test)]
mod tests {
    use super::dotenv_quote;

    #[test]
    fn dotenv_quote_preserves_argon2_hash_dollars() {
        let hash = "$argon2id$v=19$m=19456,t=2,p=1$abc$def";
        let content = format!("CRON_RS_PASSWORD={}\n", dotenv_quote(hash));
        let parsed: Vec<_> = dotenvy::from_read_iter(content.as_bytes())
            .collect::<Result<_, _>>()
            .unwrap();

        assert_eq!(
            parsed,
            vec![("CRON_RS_PASSWORD".to_string(), hash.to_string())]
        );
    }
}
